"""Constants used across the resumejson-mcp codebase.

Centralizes magic numbers and configuration values for better maintainability.
"""

# Validation thresholds
MIN_KEY_HIGHLIGHTS = 3
MAX_KEY_HIGHLIGHTS = 5
MIN_POSITION_HIGHLIGHTS = 3
RECOMMENDED_POSITION_HIGHLIGHTS = 4
MAX_POSITION_HIGHLIGHTS = 5
MIN_POSITION_COVERAGE_PCT = 70
MIN_BULLET_COVERAGE_PCT = 60

# Display formatting
SEPARATOR_LENGTH = 60
SEPARATOR_LONG = 70
STRING_TRUNCATE_PREVIEW = 50
STRING_TRUNCATE_LINE = 80
STRING_TRUNCATE_HIGHLIGHT = 70
STRING_TRUNCATE_DESCRIPTION = 100
JOB_DESCRIPTION_PREVIEW = 1000
JOB_DESCRIPTION_TRUNCATE = 2000
RENDERED_TEMPLATE_TRUNCATE = 2000
RENDERED_PREVIEW_TRUNCATE = 3000
MAX_PREVIEW_ITEMS = 5
MAX_TAG_PREVIEW = 15

# Retry and timeout
MAX_ID_COLLISION_RETRIES = 3
PDF_COMPILE_TIMEOUT_SECONDS = 60
MILLISECONDS_PER_SECOND = 1000

# Timing
MS_PER_SECOND = 1000
